### ISSUE TITLE
error in processing string labels for sex

### ISSUE THREAD

**Issue by mwvoss** [zkhan12/vo2app#4]
When I input the attached `test.csv` file I receive an error that the sex variable labels of `Female` are not recognized. README indicates `Female` should be accepted.

Example input and error:
```
(base) PSYC-M095:vo2app mwvoss$ cat ../source-data/test.csv
sex,age,vo2
Female,73,14.4
Female,71,15.2
Female,71,17.6
Female,56,13.5
```
```
(base) PSYC-M095:vo2app mwvoss$ voconv ../source-data/test.csv -o test_ku_norms.csv -s kumc
Traceback (most recent call last):
  File "/opt/anaconda3/bin/voconv", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/app_code/main.py", line 43, in main
    process_csv(opts.input, opts.o, opts.s)
  File "/opt/anaconda3/lib/python3.7/site-packages/app_code/process.py", line 40, in process_csv
    df = _get_percentiles(df, source)
  File "/opt/anaconda3/lib/python3.7/site-packages/app_code/process.py", line 63, in _get_percentiles
    percentile = get_percentile_kumc(row['sex'], row['age'], row['vomax'])
  File "/opt/anaconda3/lib/python3.7/site-packages/app_code/kumc.py", line 48, in get_percentile
    raise ValueError('Selected sex is not an option:', sex)
ValueError: ('Selected sex is not an option:', 'Female')
```

**Comment by zkhan12** [comment]
Thanks for the notification! I was able to find what was causing the error and patched it.
